#!/bin/sh

## linstallerdefault - Sets the default linstaller configuration
## Copyright (C) 2011 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


linstallerdefault ()
{
	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/linstaller.list ] || \
	   [ -e /var/lib/live/config/linstallerdefault ]
	then
		return
	fi

	echo -n " linstallerdefault"

	# Get username
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.linstallerdefault=*|linstallerdefault=*)
				CONFIG="${_PARAMETER#*linstallerdefault=}"
				;;
		esac
	done
	

	Configure_linstallerdefault
}

Configure_linstallerdefault ()
{
	
	if [ -z "$CONFIG" ]; then
		# Default to semplice
		CONFIG="semplice"
	fi
	
	# Check if configuration exists...
	if [ ! -e "/etc/linstaller/$CONFIG" ]; then
		echo "Configuration file /etc/linstaller/$CONFIG doesn't exist. Breaking here."
		exit 1
	fi
	
	# Extend $CONFIG
	# Symlink...
	ln -s /etc/linstaller/$CONFIG /etc/linstaller/default

	# Creating state file
	touch /var/lib/live/config/linstallerdefault
}

linstallerdefault
