#!/bin/sh

## linstalleralan - Configure alan to add linstaller extension to user.
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2011-2014 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

Cmdline()
{

	# Get username
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
			live-config.linstalleralan=*|linstalleralan=*)
				LIVE_ENABLE="${_PARAMETER#*linstalleralan=}"
				;;
			live-config.linstallerfrontend=*|linstallerfrontend=*)
				LIVE_FRONTEND="${_PARAMETER#*linstallerfrontend=}"
		esac
	done

}

Init() {

	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/alan2.list ] || \
	   [ -e /var/lib/live/config/linstalleralan ]
	then
		exit 0
	fi

	echo -n " linstalleralan"

}

Config ()
{
	
	if [ "$LIVE_ENABLE" != "disabled" ]; then
		# Begin.
		
		# We should first copy tree.conf from /etc/alan to /home/$LIVE_USERNAME/.config/alan.
		mkdir -p /home/$LIVE_USERNAME/.config/vera/alan # create directories
		chown -R $LIVE_USERNAME:$LIVE_USERNAME /home/$LIVE_USERNAME/.config/vera # change owner of vera directory in .config
		
		# Now we can simply add a new category, say installer and specify the extension linstaller_alan.
		cat > /home/$LIVE_USERNAME/.config/vera/alan/alan-vera.conf <<EOF
### CREATED BY linstalleralan LIVE-CONFIG SCRIPT FROM LIVE-CONFIG-LINSTALLER PACKAGE ###
[LauncherPool:launcher]
linstaller = /usr/share/applications/linstaller.desktop
EOF
	fi

	# Creating state file
	touch /var/lib/live/config/linstalleralan
}

Cmdline
Init
Config
