#!/bin/sh

## linstallersession - Sets the linstaller session
## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
## Copyright (C) 2013-2014 Eugenio "g7" Paolantonio <me@medesimo.eu>
##
## live-config-semplice comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

set -e

Cmdline()
{

	# Get username
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.linstallersession|linstallersession)
				CONFIG="y"
				;;
		esac
	done
	
}

Init() {

	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/linstaller.list ] || \
	   [ -e /var/lib/live/config/linstallersession ]
	then
		exit 0
	fi

	echo -n " linstallersession"

}

Config()
{
	
	if [ "$CONFIG" = "y" ]; then
		update-alternatives --set x-session-manager /usr/bin/linstaller_session.sh &> /dev/null
	fi

	# Creating state file
	touch /var/lib/live/config/linstallersession
}

Cmdline
Init
Config
